# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module_module_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='module',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='section',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrolment',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
