# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20160205_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Study',
            new_name='Course',
        ),
    ]
