# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20160205_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(),
        ),
    ]
